drop  view t_member                           ;
drop  view t_member_binding                   ;
drop  view t_order                            ;
drop  view t_push_job                         ;
drop  view t_refund_line                      ;
drop  view u_order                            ;
drop  view u_refund_basic                     ;
drop  view t_member_baby                      ;
drop  view t_member_base_ext                  ;
drop  view t_member_bind_unbind_history       ;
drop  view t_order_line                       ;
drop  view t_order_pay                        ;
drop  view t_pos_refund_basic                 ;
drop  view t_staff_label_his                  ;
drop  view t_staff_read_time                  ;
drop  view t_voucher                          ;
drop  view u_achievement_percentage_record    ;
drop  view u_card_item_detail                 ;
drop  view u_card_item_record                 ;
drop  view u_order_line                       ;
drop  view u_order_pay                        ;
drop  view u_refund_pay                       ;
drop 	view t_crm_asset_count         				  ;
drop 	view t_crm_consume_analyse     				  ;
drop 	view t_crm_contact_note        				  ;
drop 	view t_crm_member_info         				  ;
drop 	view t_crm_member_label        				  ;
drop 	view t_crm_permission          				  ;
drop 	view t_staff_label_his         				  ;
drop 	view t_staff_read_time         				  ;
drop 	view gb_brand 												  ;
drop 	view gb_share_item 										  ;
drop 	view gb_style 												  ;
drop 	view t_goods_type 										  ;
drop  view u_refund_basic                     ;
                                                          
                                                                                                            
create  view t_member                         as select * from    db_user.t_member                       ;
create  view t_member_binding                 as select * from    db_user.t_member_binding               ;
create  view t_order                          as select * from    db_gd_dev.t_order                        ;
create  view t_push_job                       as select * from    db_gd_dev.t_push_job                     ;
create  view t_refund_line                    as select * from    db_gd_dev.t_refund_line                  ;
create  view u_order                          as select * from    db_gd_dev.u_order                        ;
create  view u_refund_basic                   as select * from    db_gd_dev.u_refund_basic                 ;
create  view t_member_baby                    as select * from    db_user.t_member_baby                  ;
create  view t_member_base_ext                as select * from    db_user.t_member_base_ext              ;
create  view t_member_bind_unbind_history     as select * from    db_user.t_member_bind_unbind_history   ;
create  view t_order_line                     as select * from    db_gd_dev.t_order_line                   ;
create  view t_order_pay                      as select * from    db_gd_dev.t_order_pay                    ;
create  view t_pos_refund_basic               as select * from    db_gd_dev.t_pos_refund_basic             ;
create  view t_staff_label_his                as select * from    mamahao_crm.t_staff_label_his              ;
create  view t_staff_read_time                as select * from    mamahao_crm.t_staff_read_time              ;
create  view t_voucher                        as select * from    db_gd_dev.t_voucher                      ;
create  view u_achievement_percentage_record  as select * from    mamahao_pos.u_achievement_percentage_record;
create  view u_card_item_detail               as select * from    mamahao_pos.u_card_item_detail             ;
create  view u_card_item_record               as select * from    mamahao_pos.u_card_item_record             ;
create  view u_order_line                     as select * from    db_gd_dev.u_order_line                   ;
create  view u_order_pay                      as select * from    db_gd_dev.u_order_pay                    ;
create  view u_refund_pay                     as select * from    db_gd_dev.u_refund_pay                   ;
create 	view t_crm_asset_count         				as select * from    mamahao_crm.t_crm_asset_count       ;
create 	view t_crm_consume_analyse     				as select * from    mamahao_crm.t_crm_consume_analyse   ;
create 	view t_crm_contact_note        				as select * from    mamahao_crm.t_crm_contact_note      ;
create 	view t_crm_member_info         				as select * from    mamahao_crm.t_crm_member_info       ;
create 	view t_crm_member_label        				as select * from    mamahao_crm.t_crm_member_label      ;
create 	view t_crm_permission          				as select * from    mamahao_crm.t_crm_permission        ;
create 	view t_staff_label_his         				as select * from    mamahao_crm.t_staff_label_his       ;
create 	view t_staff_read_time         				as select * from    mamahao_crm.t_staff_read_time       ;
create 	view gb_brand 												as  select * from db_gd_dev.gb_brand           ;
create 	view gb_share_item 										as select * from db_gd_dev.gb_share_item  ;
create 	view gb_style 												as select * from db_gd_dev.gb_style            ;
create 	view t_goods_type 										as select * from db_gd_dev.t_goods_type    ;
create  view u_refund_basic                   as select * from db_gd_dev.u_refund_basic;