create  view t_member                         as select * from    `mamahao-user`.t_member         ;
create  view t_member_binding                 as select * from     `mamahao-user`.t_member_binding               ;
create  view t_order                          as select * from    db_gd.t_order                        ;
create or replace view t_push_job                       as select * from    db_gd.t_push_job                     ;
create  view t_refund_line                    as select * from    db_gd.t_refund_line                  ;
create  view u_order                          as select * from    db_gd.u_order                        ;
create  or replace view u_order_line                          as select * from    db_gd.u_order_line                        ;
create  view u_refund_basic                   as select * from    db_gd.u_refund_basic                 ;
create  view t_member_baby                    as select * from     `mamahao-user`.t_member_baby                  ;
create  view t_member_base_ext                as select * from     `mamahao-user`.t_member_base_ext              ;
create  view t_member_bind_unbind_history     as select * from     `mamahao-user`.t_member_bind_unbind_history   ;
create  view t_order_line                     as select * from    db_gd.t_order_line                   ;
create  view t_order_pay                      as select * from    db_gd.t_order_pay                    ;
create  view t_pos_refund_basic               as select * from    db_gd.t_pos_refund_basic             ;
create  view t_staff_label_his                as select * from    mamahao_crm.t_staff_label_his              ;
create  view t_staff_read_time                as select * from    mamahao_crm.t_staff_read_time              ;
create  view t_voucher                        as select * from    db_gd.t_voucher                      ;
create  view u_achievement_percentage_record  as select * from    `mamahao-pos`.u_achievement_percentage_record;
create  view u_card_item_detail               as select * from     `mamahao-pos`.u_card_item_detail             ;
create  view u_card_item_record               as select * from     `mamahao-pos`.u_card_item_record             ;
create  view u_order_line                     as select * from    db_gd.u_order_line                   ;
create or replace view u_order_pay                      as select * from    db_gd.u_order_pay                    ;
create  view u_refund_pay                     as select * from    db_gd.u_refund_pay                   ;
create 	view t_crm_asset_count         				as select * from    mamahao_crm.t_crm_asset_count       ;
create 	view t_crm_consume_analyse     				as select * from    mamahao_crm.t_crm_consume_analyse   ;
create 	view t_crm_contact_note        				as select * from    mamahao_crm.t_crm_contact_note      ;
create 	view t_crm_member_info         				as select * from    mamahao_crm.t_crm_member_info       ;
create 	view t_crm_member_label        				as select * from    mamahao_crm.t_crm_member_label      ;
create 	view t_crm_permission          				as select * from    mamahao_crm.t_crm_permission        ;
create 	view t_staff_label_his         				as select * from    mamahao_crm.t_staff_label_his       ;
create 	view t_staff_read_time         				as select * from    mamahao_crm.t_staff_read_time       ;
create 	view gb_brand 												as  select * from db_gd.gb_brand           ;
create 	view gb_share_item 										as select * from db_gd.gb_share_item  ;
create 	view gb_style 												as select * from db_gd.gb_style            ;
create 	view t_goods_type 										as select * from db_gd.t_goods_type    ;
create  view u_refund_basic                   as select * from db_gd.u_refund_basic;