drop table t_order;
CREATE TABLE `t_order` (
  `order_no` varchar(64) CHARACTER SET utf8 NOT NULL COMMENT '订单编号',
  `order_batch_no` varchar(64) CHARACTER SET utf8 DEFAULT NULL,
  `logic_relative_no` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '正常入库订单、拆单新单、换货新单用来关联的逻辑单号',
  `old_order_no` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '原单号',
  `serial_number` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '支付宝流水',
  `order_state` int(32) DEFAULT '3' COMMENT '订单状态 0：已完成 1：已失效 2：已取消 3：待付款 4：待发货 5：待收货 6：待评价 7：初始状态',
  `order_type` int(11) DEFAULT '1' COMMENT '1-普通订单（默认）；2-妈豆订单（不允许退款退货）；3-pos订单（包括普通POS订单、特卖会）；4-门店扫码；5-众筹订单',
  `sub_type` tinyint(4) DEFAULT '0' COMMENT '0-默认,正常入库订单；1-待发货拆出来的新单；2-换货新单',
  `scan_resource` tinyint(4) DEFAULT NULL COMMENT 'orderType=3扫码时，目前支付宝/微信直接扫码付，该值为3；APP直接扫码付，该值为入库时设置为 99',
  `order_source` int(11) DEFAULT NULL COMMENT '1:GB订单 2：mothercart订单',
  `inspect_refuse_type` int(11) NOT NULL DEFAULT '0' COMMENT '0-正常默认；1-取消订单(未选择商品进行支付操作，APP需展现)；2-拒收商品（用户发生过支付行为，APP需屏蔽掉的旧单',
  `parent_order_no` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '父订单编号',
  `split_from_no` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '从哪个订单号拆分出来的订单，类似验货付款的old_order_no',
  `split_flag` tinyint(4) DEFAULT '0' COMMENT '标识订单商品拆分标记：0-默认；1-部分拆分；2-全部拆分',
  `cod_amount` int(11) DEFAULT '0' COMMENT '货到付款的代收金额',
  `member_id` int(11) DEFAULT NULL COMMENT '会员ID',
  `member_name` varchar(64) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '会员名',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '商店id',
  `shop_name` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `shop_province` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `shop_city` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `shop_county` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `company_id` bigint(20) DEFAULT NULL COMMENT '分公司id',
  `warehouse_type` int(255) DEFAULT NULL COMMENT '1:分仓 2：总仓',
  `warehouse_id` int(11) DEFAULT NULL COMMENT '出货仓库ID',
  `warehouse_name` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '仓库名称',
  `address` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `province` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `city` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `county` varchar(10) CHARACTER SET utf8 DEFAULT NULL,
  `dealing_type` int(8) NOT NULL DEFAULT '1' COMMENT '1：线上支付，2：验货付款',
  `pay_lock_type` int(8) NOT NULL DEFAULT '0' COMMENT '每月购订单使用：0- 正常，1-验货付款待支付，2-验货付款完成',
  `need_invoice` tinyint(1) DEFAULT NULL,
  `consignee_name` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '收货人姓名',
  `consignee_phone` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `delivery_way` int(255) DEFAULT NULL COMMENT '配送方式 1：门店配送 2：上门自提 3：快递配送',
  `delivery_time` datetime DEFAULT NULL COMMENT '发货时间',
  `confirm_good_time` datetime DEFAULT NULL COMMENT '确认收货时间',
  `delay_receipt_time` datetime DEFAULT NULL COMMENT '延迟收货时间',
  `delay_receipt_day` int(11) DEFAULT '0' COMMENT '默认0；延迟收货累计天数',
  `payment_time` datetime DEFAULT NULL COMMENT '付款时间',
  `finish_time` datetime DEFAULT NULL COMMENT '交易完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '交易取消时间',
  `expire_time` datetime DEFAULT NULL COMMENT '交易失效时间',
  `invoice_type` int(1) DEFAULT NULL,
  `invoice_title` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '发票抬头',
  `remark` varchar(512) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '备注',
  `buyer_remark` varchar(360) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '买家备注',
  `pay_total_price` int(11) DEFAULT NULL,
  `pay_price` int(11) DEFAULT NULL,
  `pay_freight_price` int(11) DEFAULT NULL,
  `pay_shop_act_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `pay_shop_act_price` int(11) DEFAULT NULL,
  `pay_coupon_price` int(11) DEFAULT NULL,
  `pay_mbean_price` int(11) DEFAULT NULL,
  `pay_mbean_count` int(255) DEFAULT NULL,
  `pay_mothercare_price` int(11) DEFAULT NULL,
  `pay_mothercare_count` int(255) DEFAULT NULL,
  `pay_gb_price` int(11) DEFAULT NULL,
  `pay_gb_count` int(255) DEFAULT NULL,
  `get_integral` int(255) DEFAULT NULL,
  `coupon_id` int(11) DEFAULT NULL,
  `pay_type_id` int(11) DEFAULT NULL,
  `pay_amount` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '已删除',
  `pay_account` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `pay_shop_price` int(11) DEFAULT NULL,
  `distribution_section` int(255) DEFAULT NULL,
  `tml_num_id` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `relation_type` int(11) DEFAULT NULL COMMENT '订单类型所关联的类型： 门店扫码（1：一元购 2：多元购）；POS订单（3：特卖会）；普通订单（4-代拍、6-每月购）',
  `virtual_store_id` bigint(20) DEFAULT NULL COMMENT '接单店（供GB侧使用）',
  `pick_type` int(2) DEFAULT NULL,
  `pick_shop_id` bigint(20) DEFAULT NULL,
  `platform_source` int(1) DEFAULT '1' COMMENT '订单平台来源:（1:-APP、2-云销平台、3-微商城）',
  `flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否扫描过此表  0 未扫描  1 已扫描',
  `income_flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '分公司收入扫描标志  0 未扫描  1已扫描',
  `flag_integral` tinyint(3) NOT NULL DEFAULT '0' COMMENT '送会员等级积分,是否扫描过此表  0 未送  1 已送',
  `refund_state` int(1) DEFAULT '0' COMMENT '0：无退款（默认） 1：有退款 2：全部退款退货',
  `refund_price` int(8) DEFAULT '0',
  `mmh_bear_mail_price` int(8) DEFAULT '0',
  `deliver_prv_id` int(11) DEFAULT '0' COMMENT '发货省id',
  `receipt_prv_id` int(11) DEFAULT '0' COMMENT '收货省id',
  `shift_status` int(11) DEFAULT '0' COMMENT '是否转单 0 未转单(默认) 1 转单',
  `addrId` int(11) DEFAULT NULL,
  `cust_store_id` int(11) DEFAULT '0' COMMENT '下单店 默认0',
  `cancel_cause_id` int(2) DEFAULT NULL COMMENT '原因id',
  `cancel_remark` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '取消商品备注',
  `choose_home` int(1) DEFAULT NULL COMMENT '是否是现场验货 0：非 1：是',
  `deposit_status` int(1) DEFAULT '1' COMMENT '寄存状态 1：寄存中 2：已完成 3:已退货',
  PRIMARY KEY (`order_no`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_batch_parent` (`order_batch_no`,`parent_order_no`),
  KEY `idx_order_m3` (`consignee_name`(191),`created_time`),
  KEY `idx_order_m6` (`tml_num_id`),
  KEY `idx_order_m7` (`serial_number`),
  KEY `idx_order_m5` (`parent_order_no`,`order_type`) USING BTREE,
  KEY `idx_order_state` (`parent_order_no`,`order_state`) USING BTREE,
  KEY `idx_member_state` (`member_id`) USING BTREE,
  KEY `idx_logic_relative_no` (`logic_relative_no`),
  KEY `idx_split_from_no` (`split_from_no`) USING BTREE,
  KEY `idx_old_order_no` (`old_order_no`),
  KEY `idx_order_parent_no` (`parent_order_no`),
  KEY `idx_finish_time` (`finish_time`) USING BTREE,
  KEY `idx_order_state_single` (`order_state`),
  KEY `idx_order_mpos` (`order_source`,`order_type`),
  KEY `idx_order_m8` (`dealing_type`,`scan_resource`),
  KEY `idx_order_m9` (`platform_source`,`order_type`),
  KEY `index_shop_create` (`shop_id`,`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment 'app线上订单及gb线下扫码(查询数据仓库)';

drop table t_order_line;
CREATE TABLE `t_order_line` (
  `order_line_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单商品主键',
  `type` tinyint(4) DEFAULT NULL COMMENT '标识商品行是否处于退货状态 0-否（默认状态、退货关闭、退货完成）1 - 是（正在退货中）',
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `good_item_id` int(11) DEFAULT NULL COMMENT '商品编号',
  `item_type` int(11) DEFAULT '3' COMMENT '商品类型(1=服务，2=卡项，3=商品)',
  `good_item_name` varchar(255) DEFAULT NULL COMMENT '商品名',
  `u_order_line_id` int(11) DEFAULT NULL COMMENT 'u_order中商品行ID',
  `pre_allocated_count` int(1) DEFAULT '0' COMMENT '原始数量',
  `allocated_count` int(1) DEFAULT NULL COMMENT '全部配送数量',
  `can_split_count` int(11) DEFAULT NULL COMMENT '商品行被拆分后剩余的数量(即仍可拆分的值，只适用于拆单功能)，初始值为allocated_count',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（申请时间）',
  `pay_unit_price` decimal(10,0) DEFAULT NULL COMMENT '商品单价（单位：分）',
  `pay_total_price` decimal(10,0) DEFAULT NULL COMMENT '商品行原总价（单位：分）',
  `pay_price` decimal(10,0) DEFAULT NULL COMMENT '商品行支付价（单位：分）',
  `pure_pay_price` decimal(10,0) DEFAULT NULL COMMENT '净支付价：pay_price减去发生退款退货的金额，如果''取消退货''不再恢复该值，默认等于pay_price',
  `pay_mbean_count` varchar(255) DEFAULT NULL COMMENT '商品行使用麻豆数',
  `pay_mbean_price` int(11) DEFAULT NULL COMMENT '麻豆数抵用金额',
  `pay_mothercare_price` int(11) DEFAULT NULL COMMENT 'othercare抵扣价(单位：分)',
  `pay_mothercare_count` int(11) DEFAULT NULL COMMENT 'mothercare使用数量',
  `pay_gb_price` int(11) DEFAULT NULL COMMENT 'GB抵扣价(单位：分)',
  `pay_gb_count` int(11) DEFAULT NULL COMMENT 'GB使用数量',
  `pay_shop_act_id` varchar(255) DEFAULT NULL COMMENT '门店活动id',
  `pay_shop_act_price` decimal(10,0) DEFAULT NULL COMMENT '门店活动优惠金额（单位：分）',
  `pay_coupon_act_id` bigint(20) DEFAULT NULL COMMENT '平台优惠卷id',
  `pay_coupon_act_price` int(11) DEFAULT NULL COMMENT '平台优惠卷分摊金额（单位：分）',
  `get_integral` varchar(255) DEFAULT NULL COMMENT '获得的会员积分',
  `remark` varchar(100) DEFAULT NULL COMMENT '退款退货备注',
  `pay_pmt_price` int(11) DEFAULT '0' COMMENT '促销价',
  `pmt_all_reduce_price` int(11) DEFAULT NULL,
  `pmt_part_reduce_price` int(11) DEFAULT NULL,
  `pmt_group_price` int(11) DEFAULT NULL,
  `pmt_buy_more_price` int(11) DEFAULT NULL COMMENT '多买促销优惠金额',
  `pmt_sale_price` int(11) DEFAULT NULL,
  `pay_vip_reduce_price` int(11) DEFAULT '0' COMMENT 'VIP会员优惠价(每月购)',
  `vip_amount` int(11) DEFAULT '0' COMMENT '超级VIP优惠金额',
  `pay_shop_price` int(11) DEFAULT '0' COMMENT '店铺销售金额，即平台应打给店铺的金额(单位：分)',
  `give_mbean_count` int(11) DEFAULT '0' COMMENT '赠送妈豆数量',
  `pay_group_coupon_price` int(11) DEFAULT '0' COMMENT '集团优惠券承担金额',
  `pay_mmh_coupon_price` int(11) DEFAULT '0' COMMENT '妈妈好优惠券承担金额',
  `pmt_purchase_price` int(11) DEFAULT '0' COMMENT '每月购优惠金额',
  `pmt_random_reduce_price` int(11) DEFAULT '0' COMMENT '扫码付订单随机立减优惠',
  `sub_pay_price` int(11) DEFAULT '0' COMMENT '合作商支付金额',
  `is_gift` int(11) DEFAULT '0' COMMENT '是否是赠品（0：否 1：是） 默认0',
  `from_id` int(11) DEFAULT '0' COMMENT '发源地id',
  `refuse_receive` int(2) DEFAULT '0' COMMENT '0:正常， 1：截单拒收， 2：签收拒收',
  `purchase_flag` tinyint(1) DEFAULT '0' COMMENT '是否每月购商品；0-不是、1-每月购商品',
  `pmt_purchase_type` int(2) DEFAULT '0' COMMENT '0：不参加套餐；1：新生儿套餐；2：每月购（具体月份根据created_time来确定）',
  `pmt_purchase_free` tinyint(2) DEFAULT '0' COMMENT '免费商品标识：pmt_purchase_type为1,2时，可能为true',
  `cancel_remark` varchar(50) DEFAULT NULL COMMENT '取消商品备注',
  `cancel_cause_id` int(2) DEFAULT NULL COMMENT '原因id',
  `cart_item_pid` int(8) DEFAULT NULL COMMENT '购物车商品主键id',
  `split_from_line_id` int(11) DEFAULT NULL COMMENT '从哪个商品行拆分出来的新商品行,适用于未参与赠品促销的拆单',
  PRIMARY KEY (`order_line_id`),
  KEY `IDX_ITEM_ID` (`order_no`,`good_item_id`) USING BTREE,
  KEY `good_item_id` (`good_item_id`),
  KEY `IDX_CREATE_TIME` (`created_time`),
  KEY `IDX_u_order_line` (`u_order_line_id`),
  KEY `index_order_no` (`order_no`)
) ENGINE=InnoDB AUTO_INCREMENT=2754706 DEFAULT CHARSET=utf8 comment '线上订单商品(查询数据仓库）';


drop table t_order_pay;
CREATE TABLE `t_order_pay` (
  `order_no` varchar(64) NOT NULL COMMENT '订单编号',
  `pay_total_price` int(11) DEFAULT NULL COMMENT '订单总价(单位：分)',
  `pay_price` int(11) DEFAULT NULL COMMENT '订单支付价(单位：分)',
  `pay_freight_price` int(11) DEFAULT NULL COMMENT '运费(单位：分)',
  `redu_pay_freight_price` int(11) DEFAULT NULL COMMENT '被抵扣的邮费',
  `install_price` int(11) DEFAULT NULL COMMENT '安装费',
  `redu_install_price` int(11) DEFAULT NULL COMMENT '被抵扣的安装费',
  `pay_shop_act_id` varchar(255) DEFAULT NULL COMMENT '门店活动id',
  `pay_shop_act_price` int(11) DEFAULT NULL COMMENT '门店活动优惠金额(单位：分)',
  `coupon_id` int(11) DEFAULT NULL COMMENT '使用的优惠券id',
  `pay_coupon_price` int(11) DEFAULT NULL COMMENT '优惠券优惠金额(单位：分)',
  `pay_mbean_price` int(11) DEFAULT NULL COMMENT '麻豆抵扣价(单位：分)',
  `pay_mbean_count` int(11) DEFAULT NULL COMMENT '麻豆使用数量',
  `pay_mothercare_price` int(11) DEFAULT NULL COMMENT 'mothercare抵扣价(单位：分)',
  `pay_mothercare_count` int(255) DEFAULT NULL COMMENT 'mothercare使用数量',
  `pay_gb_price` int(11) DEFAULT NULL COMMENT 'GB抵扣价(单位：分)',
  `pay_gb_count` int(255) DEFAULT NULL COMMENT 'GB使用数量',
  `get_integral` int(11) DEFAULT NULL COMMENT '获得的会员积分',
  `pay_type_id` int(11) DEFAULT NULL COMMENT '支付类型，见字典表（暂时未用）',
  `sub_pay_type_id` int(11) DEFAULT '0' COMMENT '合作商支付类型，1:ucan；-99:未知服务方',
  `mch_id` varchar(32) DEFAULT NULL COMMENT '商户支付账户，目前微信在使用',
  `pay_account` varchar(50) DEFAULT NULL,
  `pay_shop_price` int(11) DEFAULT NULL COMMENT '店铺销售金额，即平台应打给店铺的金额(单位：分)',
  `distribution_section` int(2) DEFAULT NULL COMMENT '配送时间段，见字典表',
  `pmt_all_reduce_price` int(11) DEFAULT NULL,
  `pmt_part_reduce_price` int(11) DEFAULT NULL,
  `pmt_group_price` int(11) DEFAULT NULL,
  `pmt_buy_more_price` int(11) DEFAULT NULL COMMENT '多买促销优惠金额',
  `pmt_sale_price` int(11) DEFAULT NULL,
  `pmt_purchase_type` int(2) DEFAULT NULL COMMENT '0：普通商品；1：新生儿套餐；2：每月购（具体月份根据created_time来确定）',
  `pmt_purchase_price` int(11) DEFAULT '0' COMMENT '每月购优惠金额',
  `pmt_random_reduce_price` int(11) DEFAULT '0' COMMENT '扫码付订单随机立减优惠',
  `pmt_random_reduce_cost` int(11) DEFAULT NULL COMMENT '扫码付订单随机立减承担方：0:好孩子集团承担 1:妈妈好平台承担 2:发货方承担-走好孩子集团承担逻辑',
  `sub_pay_price` int(11) DEFAULT '0' COMMENT '合作商支付金额',
  `pay_wechat_card_coupon_qrcode` varchar(20) DEFAULT '' COMMENT '微信卡劵二维码信息',
  `pay_vip_reduce_price` int(11) DEFAULT '0' COMMENT 'VIP会员优惠价(每月购)',
  `vip_amount` int(11) DEFAULT '0' COMMENT '超级VIP优惠',
  `refund_amount` int(11) DEFAULT '0' COMMENT '退款金额',
  `pay_group_coupon_price` int(11) DEFAULT '0' COMMENT '集团优惠券承担金额',
  `pay_mmh_coupon_price` int(11) DEFAULT '0' COMMENT '妈妈好优惠券承担金额',
  PRIMARY KEY (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 comment '线上订单金额(查询数据仓库)';




drop table u_order;
CREATE TABLE `u_order` (
  `order_no` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单号',
  `app_order_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '小票号，记录妈妈好三级订单号',
  `stl_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '结算时使用的单号',
  `document_type` tinyint(4) DEFAULT NULL COMMENT '单据类型，0=散客，1=会员',
  `mmh_member_id` int(11) DEFAULT NULL COMMENT '妈妈好会员ID',
  `member_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '妈妈好会员name',
  `member_phone` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'upos会员手机号',
  `order_state` tinyint(4) DEFAULT NULL COMMENT '0-已完成;1-已失效(未使用);2-已取消;3-待付款;4-待发货;5-待收货;6-结算单被挂起;7-待评价',
  `order_type` tinyint(4) DEFAULT NULL COMMENT '订单类型(1-upos门店订单；2-APP购买的充值卡项；3-升卡单)',
  `order_channel` tinyint(4) DEFAULT NULL COMMENT '订单渠道(1-线下门店pos机；2-妈妈好APP)',
  `resource` tinyint(4) DEFAULT NULL COMMENT '订单支付方式为支付宝/微信时此值有参考意义：3-支付宝/微信直接扫码；99-APP直接扫码；',
  `s_id` int(11) DEFAULT NULL COMMENT '发货体id',
  `s_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发货体名称',
  `s_type` tinyint(4) DEFAULT NULL COMMENT '发货体类型(2=门店，3=仓库)',
  `s_company_id` int(11) DEFAULT NULL COMMENT '发货体分公司id',
  `s_company_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发货体分公司名称',
  `delivery_way` tinyint(4) DEFAULT NULL COMMENT '发货类型(1=配送，2=自提，3=快递)',
  `s_prv_id` int(11) DEFAULT NULL COMMENT '发货体省id（供后续统计使用）',
  `s_city_id` int(11) DEFAULT NULL COMMENT '发货体市id（供后续统计使用）',
  `s_area_id` int(11) DEFAULT NULL COMMENT '发货体区id（供后续统计使用）',
  `sys_remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单备注-系统',
  `create_time` datetime DEFAULT NULL COMMENT '订单创建时间',
  `pay_time` datetime DEFAULT NULL COMMENT '订单支付时间',
  `close_time` datetime DEFAULT NULL COMMENT '订单取消、失效时间',
  `delivery_time` datetime DEFAULT NULL COMMENT 'delivery_time',
  `update_time` datetime DEFAULT NULL COMMENT '订单更新时间',
  `comfirm_time` datetime DEFAULT NULL,
  `success_time` datetime DEFAULT NULL,
  `transfer_deposit_time` datetime DEFAULT NULL COMMENT '转为寄存订单时间',
  `collect_price` int(11) DEFAULT NULL COMMENT '收取用户的现金（分）',
  `return_price` int(11) DEFAULT NULL COMMENT '找零给用户的现金（分）',
  `pos_num` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '生成订单的POS机编号',
  `umember_id` int(11) DEFAULT NULL COMMENT 'upos会员id',
  `card_number` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'upos会员卡号',
  `cashier_baby_name` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '收银填写的宝宝名称',
  PRIMARY KEY (`order_no`),
  KEY `idx_order_no` (`order_no`) USING BTREE,
  KEY `idx_orderStatus` (`order_state`),
  KEY `idx_orderType` (`order_type`),
  KEY `idx_orderSId` (`s_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment 'pos订单(查询数据仓库)';





drop table u_order_line;
CREATE TABLE `u_order_line` (
  `order_line_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单商品表id，自增id',
  `app_order_line_id` int(11) DEFAULT NULL COMMENT '同步到app订单接口后，映射的商品行id',
  `order_no` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单号',
  `stl_line_id` bigint(11) DEFAULT NULL COMMENT '结算单中的商品行id',
  `mmh_member_id` int(11) DEFAULT NULL COMMENT '妈妈好会员ID',
  `emp_id` int(11) DEFAULT NULL COMMENT '服务员工id',
  `emp_name` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cashier_emp_id` int(11) DEFAULT NULL COMMENT '收银员员工id',
  `cashier_emp_name` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item_id` int(11) NOT NULL COMMENT '商品id',
  `item_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品名称',
  `item_type` int(2) NOT NULL COMMENT '商品类型(1=服务，2=卡项)',
  `item_sku` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'itemType=3商品时的sku',
  `item_pic` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'itemType=3商品时的主图',
  `card_type` int(2) DEFAULT NULL COMMENT '卡项类型，0=储值卡，1=次数卡，2=时间卡，3=综合卡，4=赠送卡',
  `service_type` int(11) DEFAULT NULL COMMENT '服务类型0:儿童推拿， 1：活动项目，2：儿童理发，3：儿童游泳， 4：成人推拿， 5：婴幼儿游泳',
  `item_count` int(11) NOT NULL COMMENT '商品数量',
  `acquire_count` int(11) DEFAULT NULL COMMENT '已领取数量（针对寄存单)',
  `gift_type` int(2) NOT NULL DEFAULT '0' COMMENT '赠品类型(0=普通商品，1=赠品)',
  `item_unit_price` int(11) NOT NULL COMMENT '商品吊牌价(单位：分)，StlItemDto.unitPrice',
  `direct_sale_price` int(11) DEFAULT '0' COMMENT '商品直卖单价，不包含议价、VIP价、各种促销',
  `act_price` int(11) DEFAULT NULL COMMENT '活动价格（收银台的“单价”），StlItemDto.itemPrice',
  `dis_price` int(11) DEFAULT NULL COMMENT '收银台的“项目金额”，StlItemDto.sumPayPrice = actPrice * count * vipDiscount',
  `payable_amount` int(11) DEFAULT NULL COMMENT '应付金额（收银员填写的价格），在此价格的基础上做促销政策的匹配 StlItemDto.newSumPayPrice',
  `pay_price` int(11) DEFAULT NULL COMMENT 'payableAmount参与各种促销后的价格，StlItemDto.payPrice',
  `should_amount` int(11) DEFAULT NULL COMMENT 'payPrice减去优惠券/积分后，用户最后应付金额',
  `payment_amount` int(11) DEFAULT NULL COMMENT 'shouldAmount四舍五入处理后的入库金额',
  `free_amount` int(11) DEFAULT '0' COMMENT '免额金额',
  `debt_amount` int(11) DEFAULT '0' COMMENT '欠款金额',
  `vip_discount` float DEFAULT '1' COMMENT '会员折扣(如：0.8)',
  `refund_state` tinyint(2) NOT NULL DEFAULT '0' COMMENT '退款状态，记录实际退款完成的(0=未退款，1=部分退款，2=全部退款，3 = 被升卡)',
  `exchange_state` tinyint(4) NOT NULL DEFAULT '0' COMMENT '换货状态，(0=未换货，1=部分换货，2=全部换货)',
  `debt_status` tinyint(4) DEFAULT NULL COMMENT '商品欠款标记（0-未欠款；1-欠款未补缴；2-欠款补缴待支付；3-欠款补缴完成；4-欠款还款结算挂起）',
  `comment_state` tinyint(2) DEFAULT NULL COMMENT '评价状态，0=未评价 ，1=已评价',
  `comment_score` tinyint(2) DEFAULT NULL COMMENT '评价 0:满意 1:一般 2:不满意',
  `comment_tag` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '冗余字段，评价标签，满意，一般等',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `give_mbean_count` int(11) DEFAULT '0' COMMENT '赠送的积分数量',
  `remark` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品备注',
  `umember_id` int(11) DEFAULT NULL COMMENT 'upos会员id',
  `documents_id` int(11) DEFAULT NULL COMMENT '所属的挂单id',
  `documents_detail_id` int(11) DEFAULT NULL COMMENT '冗余字段',
  PRIMARY KEY (`order_line_id`),
  KEY `Index_emp_id` (`emp_id`),
  KEY `Index_order_no` (`order_no`),
  KEY `Index_umemberId` (`umember_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12828 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment 'pos订单商品(查询数据仓库)';




drop table u_order_pay;
CREATE TABLE `u_order_pay` (
  `order_pay_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '支付信息表id，自增id',
  `order_no` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单号',
  `common_id` bigint(30) DEFAULT NULL COMMENT '通用id (优惠券id，卡项服务id，支付宝或微信账户id)',
  `common_value` int(11) DEFAULT NULL COMMENT '通用值 (次数，个数，金额分)',
  `offset_price` int(11) DEFAULT NULL COMMENT 'common_value抵消支付金额（单位：分）',
  `pay_type` int(2) DEFAULT NULL COMMENT '支付/促销类型(1-支付宝;2-微信;3-银联;4-会员卡;5-优惠券;6-积分;7-团购;8-现金;9-银行卡;101-卡项折扣;102-会员折扣;103-直降;104-满减;105-买赠;106-满返;107-满赠;108-议价;109-多买;110-买返比率券)',
  `pay_serial_number` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '支付流水号',
  `payment_type` int(2) NOT NULL DEFAULT '0' COMMENT '缴费类型(0=正常支付，1=欠款补缴)',
  `extend_field1` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '预留（通用逻辑）：pay_type=110时返的百分比券id；pay_type=4时(卡项消费渠道)1-扫描APP付款码、2-用户输入密码；pay_type=107满赠时，记录levelId；107满返时，记录levelId-couponTemplate',
  `extend_field2` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '预留字段（通用逻辑处理）：pay_type=106/110时，赠送的优惠券id',
  PRIMARY KEY (`order_pay_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB AUTO_INCREMENT=18879 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment 'POS订单金额(查询数据仓库)';




drop table t_refund_line；
CREATE TABLE `t_refund_line` (
  `refund_line_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '退款或退款退货记录表id主键',
  `refund_line_no` varchar(255) NOT NULL COMMENT '退款编号',
  `apply_member_id` int(11) DEFAULT NULL COMMENT '用户id',
  `refund_type` tinyint(2) NOT NULL COMMENT '退款类型 1-退货退款；2-退款；3-待发货拆单商品；4-换货单商品',
  `delivery_way` tinyint(2) DEFAULT NULL COMMENT '配送方式 1：门店配送 2：上门自提 3：快递配送',
  `refund_way` tinyint(2) DEFAULT NULL COMMENT '上门自提退货方式 1：门店上门取件退货 2：自己送货到门退货 3：快递上门取件退货',
  `status` tinyint(2) DEFAULT NULL COMMENT '退款单状态 1：退货申请审核中（即等待商家审核）2：审核通过（等待买家处理；转单退货单审核通过还表示“待运营取件”）3：退款中（同意退款，待财务打款）4：退款完成（退款完成，财务打款完成）5：审核通过超时未退货（超过15天，退款关闭）6: 取消申请（退款关闭）7: 待平台收货（非转单的退货单当refundWay =1 和 2 时，审核通过直接到 7待平台收货）8：未通过审核的关闭（退款关闭）9：部分退货中（平台已收货状态前一步骤）10：退货或退款调用GB接口失败（调用退款接口异常）11：等待客服介入（验货出现异常，数量不匹配或有损伤）12：运营取件确认（转单门店已收到退货商品）13：运营拒绝退款',
  `exchange_status` tinyint(2) DEFAULT NULL COMMENT '1-等待客服分配（用户提交换货申请，原门店库存不足需要运营分配）; 2-等待商家审核（用户提交换货申请，原门店库存充足，或客服分配后）; 3-等待买家处理（商家审核通过，快递退还商家，或用户送货到门店）; 4-等待商家验货（用户已提交物流信息，或用户送货到门店，或门店上门通过审核尚未发货的换货单）其中快递包含(快递100已推送签收仓库未操作签收商品）和(快递100已推送签收仓库也已操作签收商品）【快递是否签收参见sub_status】; 5-等待客服介入（用户申请的换货商品数量与商家收到的商品数量不一致）; 6-已验货待商家发货（商家已推送商品签收信息，新商品尚未发货）; 7-已发货待买家收货（新商品商家已发货，待买家签收）; 8-换货成功; 9-用户取消换货; 10-未通过审核关闭; 11-超时关闭; 12-转单门店已拿回换货商品，待申请退回仓库（转单）; 13-该商品原门店无库存（用户上门换货专用）;14-影响二次消费而关闭;15-商品下架而换货单关闭;16-转单门店已拿回换货商品，并提交了快递信息等待仓库验货; 99-换货关闭;',
  `exchange_dispatch_flag` tinyint(2) DEFAULT '0' COMMENT '重新申请换货单时，需走运营审核的标识：0-默认，正常情况；1-需运营审核标识；主要考虑用户提交换货申请时，仓库系统库存与实际库存不一致情况',
  `nopwd_refund_flag` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否标记为无密退款  0 有密 1 无密',
  `sub_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '退款状态的子状态 , 仅在等待商家验货会更新， 0 初始状态  1：未签收等待验货 2 ：已签收等待验货 ',
  `pay_status` int(2) DEFAULT '0' COMMENT '打款状态：0：初始状态 3：退款中（同意退款） 4：退款完成（同意退款）',
  `refund_shift_status` int(2) DEFAULT '0' COMMENT '是否转单 0 未转单(默认) 1 转单',
  `order_no` varchar(100) NOT NULL COMMENT '子订单编号',
  `order_line_id` int(11) NOT NULL COMMENT '订单商品id（good_item_id）',
  `real_order_line_id` int(11) DEFAULT '0' COMMENT '订单商品主键',
  `order_dealing_type` tinyint(2) NOT NULL COMMENT '订单的支付类型，0线上支付，1线下支付',
  `refund_serial_number` varchar(100) DEFAULT NULL COMMENT '退款支付宝流水号',
  `refund_cause` varchar(255) DEFAULT NULL COMMENT '退款原因，用户选择',
  `pre_refund_amount` double(24,2) DEFAULT NULL COMMENT '用户申请退款金额',
  `refund_amount` double(24,2) DEFAULT NULL COMMENT '实际退款金额',
  `pay_type_id` int(11) DEFAULT NULL COMMENT '支付类型 0：支付宝支付（兼容V1.0版本） 1：银联支付 2：微信支付 3：妈豆支付 4：新支付宝支付（V1.1版本） 5：微信公众号支付 6：测试支付宝支付 7：代拍支付 8：测试微商城jsapi支付 9：正式微商城jsapi支付',
  `refund_account` varchar(50) DEFAULT NULL COMMENT '退款账户（订单支付账户）',
  `refund_remark` varchar(255) DEFAULT NULL COMMENT '退款说明，用户填写',
  `refund_pic_buffer` varchar(1024) DEFAULT NULL COMMENT '退款图片，多张图片用英文逗号隔开',
  `not_pass_cause` varchar(255) DEFAULT NULL COMMENT '没有通过审核的原因',
  `goods_receipt_platform_name` varchar(50) DEFAULT NULL COMMENT '寄件地址的平台名称',
  `goods_receipt_phone` varchar(20) DEFAULT NULL COMMENT '寄件地址的联系电话',
  `goods_receipt_zip_code` varchar(6) DEFAULT NULL COMMENT '寄件地址的邮编',
  `goods_receipt_addr` varchar(255) DEFAULT NULL COMMENT '寄件地址',
  `goods_receipt_remark` varchar(255) DEFAULT NULL COMMENT '寄件备注',
  `apply_time` datetime DEFAULT NULL COMMENT '创建时间（申请时间）',
  `shop_handle_time` datetime DEFAULT NULL COMMENT '商家处理时间（审核时间）',
  `customer_handle_time` datetime DEFAULT NULL COMMENT '买家处理时间（3-快递退货时：提交物流时间；1-门店上门取件/2-用户送货到店时：与审核通过时间相同）',
  `receipt_time` datetime DEFAULT NULL COMMENT '平台收货时间',
  `end_time` datetime DEFAULT NULL COMMENT '完成时间（包括正常退款完成时间 或者 退款关闭时间）',
  `platform_time` datetime DEFAULT NULL COMMENT '客服介入时间',
  `refund_time` datetime DEFAULT NULL COMMENT '财务操作退款时间',
  `pick_user` varchar(20) DEFAULT NULL COMMENT '门店上门取件人',
  `pick_shop` varchar(50) DEFAULT NULL COMMENT '商品所属店铺',
  `pick_tel` varchar(20) DEFAULT NULL COMMENT '联系方式',
  `pick_arrive_time` datetime DEFAULT NULL COMMENT '预计到达时间',
  `gb_back_tml_num_id` varchar(255) DEFAULT NULL COMMENT 'gb退货小票单号',
  `mailPrice` decimal(10,0) DEFAULT '0' COMMENT '退还邮费（包含在退还金额之中，退货单时，mailPrice总是为0；退款单时，若退还所有商品则为下单时用户支付的邮费）',
  `pre_refund_goods_count` int(4) DEFAULT '0' COMMENT '用户申请退货数',
  `refund_goods_count` int(4) DEFAULT '0' COMMENT '实际退货数量',
  `pre_mbean` int(11) DEFAULT '0' COMMENT '用户申请退还妈豆数',
  `mbean` int(11) DEFAULT '0' COMMENT '实际退妈豆数',
  `pre_mbean_price` int(11) DEFAULT '0' COMMENT '用户申请退还妈豆金额',
  `mbean_price` int(11) DEFAULT '0' COMMENT '实际退妈豆金额',
  `pre_gb_count` int(11) DEFAULT '0' COMMENT '用户申请退还GB积分',
  `gb_count` int(11) DEFAULT '0' COMMENT '实际退GB积分',
  `pre_gb_price` int(11) DEFAULT '0' COMMENT '用户申请退还GB金额',
  `gb_price` int(11) DEFAULT '0' COMMENT '实际退GB金额',
  `pre_mc_count` int(11) DEFAULT '0' COMMENT '用户申请退还MC积分',
  `mc_count` int(11) DEFAULT '0' COMMENT '实际退MC积分',
  `pre_mc_price` int(11) DEFAULT '0' COMMENT '用户申请退还MC金额',
  `mc_price` int(11) DEFAULT '0' COMMENT '实际退还MC金额',
  `member_card_price` int(11) DEFAULT '0' COMMENT '用户使用会员卡支付金额（目前UCAN）',
  `member_card_type` int(11) DEFAULT NULL COMMENT '会员卡类型 1 UCAN',
  `shop_amount` int(11) DEFAULT NULL COMMENT '门店实际退款金额',
  `pay_group_coupon_price` int(11) DEFAULT '0' COMMENT '集团优惠券承担金额',
  `pay_mmh_coupon_price` int(11) DEFAULT '0' COMMENT '妈妈好优惠券承担金额',
  `refund_platform_type` int(1) DEFAULT '1' COMMENT '1：妈妈好 2：众筹',
  `pick_prv_id` int(8) DEFAULT NULL COMMENT '退货时用户填写的要门店上门取货的省id（POS扫码订单使用）',
  `pick_city_id` int(8) DEFAULT NULL COMMENT '退货时用户填写的要门店上门取货的市id（POS扫码订单使用）',
  `pick_area_id` int(8) DEFAULT NULL COMMENT '退货时用户填写的要门店上门取货的区id（POS扫码订单使用）',
  `pick_addr` varchar(255) DEFAULT NULL COMMENT '退货时用户填写的要门店上门取货的详细地址（POS扫码订单使用）',
  `bear_power_status` int(2) DEFAULT '1' COMMENT '承担邮费的开关，1：承担信息生效，2：不用关注承担信息',
  `have_gift` int(11) DEFAULT '0' COMMENT '是否存在赠品（促销V2 新增）0：无 1：有 （默认0）',
  `refused_flag` tinyint(4) DEFAULT '0' COMMENT '无效退货单标识:0-否(默认),1-需要运营介入（针对审核失败等其他接口调用失败导致用户再次申请的情况）  2=表示废弃记录（针对需要废弃的记录，GB推送消息延迟导致状态不同步的情况）',
  `apply_username` varchar(16) DEFAULT NULL COMMENT '通过运营后台发起退款、退货单的运营账户，默认为空',
  `update_time` datetime DEFAULT NULL,
  `refund_cause_id` int(11) DEFAULT NULL COMMENT '退货原因ID，用来判定退货原因是否支持运费赔付',
  `customer_calc_state` tinyint(2) DEFAULT '0' COMMENT '是否完全退货：0（默认）：未经历过修改金额过程 1：经历过修改金额过程',
  `rl_remark` varchar(256) DEFAULT NULL COMMENT '退货退款备注（运营后台使用）',
  `alipay_name` varchar(30) DEFAULT NULL COMMENT '用户真实姓名(运费赔付使用)',
  `alipay_account` varchar(100) DEFAULT NULL COMMENT '用户支付宝账户(运费赔付使用)',
  `bear_mail_price` int(8) NOT NULL DEFAULT '0' COMMENT '用户快递退货运费(运费赔付使用)',
  `bear_mail_price_type` int(2) NOT NULL DEFAULT '0' COMMENT '快递退货运费承担方 1：妈妈好 2：分公司 3：仓库 4：用户',
  `logistics_type` varchar(50) DEFAULT NULL COMMENT '退货的物流平台类型，具体对应待定',
  `logistics_name` varchar(50) DEFAULT NULL COMMENT '退货的物流平台名称',
  `logistics_number` varchar(100) DEFAULT '' COMMENT '退货的物流单号',
  `return_goods_time` datetime DEFAULT NULL COMMENT '部分退货最后更新时间，用这个时间来判断客户介入',
  `discount_amount` int(11) DEFAULT '0' COMMENT '总优惠金额',
  `sys_split_time` datetime DEFAULT NULL COMMENT '运营分配审核时间',
  `shop_push_goods_time` datetime DEFAULT NULL COMMENT '商家发货时间',
  `dss_push_goods_to_sys_time` datetime DEFAULT NULL COMMENT '换货成功，寄回已换商品的时间',
  PRIMARY KEY (`refund_line_id`,`refund_line_no`),
  KEY `index_real_order_line_id` (`real_order_line_id`) USING BTREE,
  KEY `idx_order_no` (`order_no`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=56591 DEFAULT CHARSET=utf8 comment 'app正常订单退款表(查询数据仓库)';

drop table t_pos_refund_basic;
CREATE TABLE `t_pos_refund_basic` (
  `pos_refund_no` varchar(64) NOT NULL COMMENT '退款编号（一个pos_gb_back_tml_num_id对应一个pos_refund_no）',
  `pos_refund_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '退款id主键（对应于pos_gb_back_tml_num_id的多次提交）',
  `pos_refund_order_no` varchar(64) DEFAULT NULL COMMENT '订单号',
  `pos_refund_batch_no` varchar(64) DEFAULT NULL COMMENT '交易流水号用于支付宝-微信逻辑处理',
  `pos_refund_logic_no` varchar(64) DEFAULT NULL COMMENT 'POS逻辑关联，POS一次退货生成一个',
  `pos_refund_type` tinyint(2) DEFAULT '1' COMMENT 'pos退款单类型 1 扫码付退单 2 POS同步订单',
  `pos_sid` int(11) DEFAULT NULL COMMENT '门店或仓库id',
  `pos_sname` varchar(255) DEFAULT NULL COMMENT '门店或仓库名称',
  `pos_stype` tinyint(4) DEFAULT '0' COMMENT '仓库类型，0：门店（默认） 1:分仓 2：总仓',
  `pos_refund_amount` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，退款金额（人民币分）',
  `pos_refund_total_amount` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，退款金额（人民币分），此退货小票累计总金额',
  `pos_refund_gb_point_count` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，gb积分（个）',
  `pos_refund_total_gb_point_count` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，gb积分（个），此退货小票累计总积分',
  `pos_refund_mc_point_count` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，mc积分（个）',
  `pos_refund_total_mc_point_count` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，mc积分（个），此退货小票累计总积分',
  `pos_refund_mbean_count` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，妈豆数量（个）',
  `pos_refund_total_mbean_count` int(11) NOT NULL DEFAULT '0' COMMENT '默认值0，妈豆数量（个），此退货小票累计总妈豆',
  `pos_member_card_amount` int(11) DEFAULT '0' COMMENT '会员卡支付金额',
  `pos_card_type` tinyint(2) DEFAULT NULL COMMENT '会员卡类型：1 UCAN会员卡',
  `pos_refund_pay_type_id` int(11) DEFAULT NULL COMMENT '支付类型 与订单支付类型匹配',
  `pos_refund_serial_number` varchar(100) DEFAULT NULL COMMENT '交易流水号',
  `pos_refund_member_id` bigint(20) DEFAULT NULL COMMENT '用户id',
  `pos_member_phone` varchar(64) DEFAULT NULL COMMENT '用户手机号',
  `pos_refund_status` int(11) NOT NULL COMMENT '退款单状态 1：待打款 2：打款完成',
  `pos_gb_back_tml_num_id` varchar(100) NOT NULL COMMENT 'gb退款小票',
  `pos_gb_primary_key` varchar(100) NOT NULL COMMENT 'gb序列号',
  `pos_refund_remark` varchar(100) DEFAULT NULL COMMENT '备注',
  `pos_create_time` datetime NOT NULL COMMENT '创建时间',
  `pos_pay_time` datetime DEFAULT NULL COMMENT '打款时间',
  `pos_refund_source` int(11) DEFAULT '1' COMMENT '退款来源 1 POS扫码付退款 3 POS换货退款（order_no对应的是换货单号）',
  PRIMARY KEY (`pos_refund_id`),
  KEY `pos_refund_no` (`pos_refund_no`),
  KEY `pos_refund_order_no` (`pos_refund_order_no`),
  KEY `pos_refund_batch_no` (`pos_refund_batch_no`),
  KEY `pos_refund_member_id` (`pos_refund_member_id`),
  KEY `pos_gb_back_tml_num_id` (`pos_gb_back_tml_num_id`),
  KEY `pos_refund_serial_number` (`pos_refund_serial_number`),
  KEY `pos_gb_primary_key` (`pos_gb_primary_key`)
) ENGINE=InnoDB AUTO_INCREMENT=350 DEFAULT CHARSET=utf8 COMMENT='gb退款单据主表-POS扫码付';






drop table u_refund_basic；
CREATE TABLE `u_refund_basic` (
  `refund_line_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '退款主表id（自增主键）',
  `refund_no` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT '退款编号',
  `refund_status` tinyint(2) DEFAULT NULL COMMENT '退款状态 0:已完成 1:退款失败',
  `refund_type` tinyint(2) DEFAULT NULL COMMENT '退款类型',
  `refund_item_type` tinyint(2) DEFAULT NULL COMMENT '退款商品类型  1=服务，2=卡项',
  `refund_way` tinyint(2) DEFAULT NULL COMMENT '退款方式：1：门店上门取件退货 2：自己送货到门退货 3：快递上门取件退货',
  `order_no` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '订单号',
  `order_line_id` int(11) DEFAULT NULL COMMENT '商品行号',
  `delivery_way` tinyint(2) DEFAULT NULL COMMENT '发货类型(1=配送，2=自提，3=快递)',
  `staff_id` int(11) DEFAULT NULL COMMENT '员工id',
  `staff_name` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '员工姓名',
  `s_id` int(11) DEFAULT NULL COMMENT '发货体id',
  `s_name` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '发货体名称',
  `s_type` tinyint(2) DEFAULT NULL COMMENT '发货体类型',
  `u_member_id` int(11) DEFAULT NULL COMMENT 'Ucan会员ID',
  `mmh_member_id` int(11) DEFAULT NULL COMMENT '妈妈好会员ID',
  `member_phone` varchar(11) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户手机号',
  `refund_cause` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '退款原因',
  `pick_up_flag` tinyint(2) DEFAULT NULL COMMENT '寄存商品提取标识 0 未取 1 已取',
  `remark` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `pay_time` datetime DEFAULT NULL COMMENT '退款时间',
  PRIMARY KEY (`refund_line_id`),
  KEY `idx_order_no` (`order_no`) USING BTREE,
  KEY `idx_refund_no` (`refund_no`) USING BTREE,
  KEY `idx_orderId` (`order_line_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1782 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment 'mpos的退货单(查询数据仓库)';


drop table u_card_item_record;
CREATE TABLE `u_card_item_record` (
  `card_item_record_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '卡项购买记录id,主键',
  `order_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '卡项充值购买订单号',
  `order_line_id` int(11) DEFAULT NULL,
  `mmh_member_id` int(11) DEFAULT NULL COMMENT '妈妈好会员id',
  `member_phone` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '会员手机号',
  `card_item_type` tinyint(4) DEFAULT NULL COMMENT '卡项类型（0=储值卡，1=次数卡，2=时间卡，3=综合卡，4=赠送卡）',
  `card_item_name` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '卡项名称',
  `card_item_template_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '卡项模板id（卡项的基础信息）',
  `face_value` int(11) DEFAULT NULL COMMENT '卡项面额(分)',
  `buy_price` int(11) DEFAULT NULL COMMENT '卡项购买付款金额(分）',
  `valid_time` datetime DEFAULT NULL COMMENT '卡项有效期（购买时间+卡项模板的有效天数）',
  `enable_status` int(2) DEFAULT '1' COMMENT '启用状态，0=未启用，1=启用',
  `status` tinyint(4) DEFAULT NULL COMMENT '卡项状态：0-正常(默认值)；1-被用完；2-退卡；3-被并卡；4-退卡后重新激活',
  `create_time` datetime DEFAULT NULL COMMENT '提交购买时间',
  `buy_time` datetime DEFAULT NULL COMMENT '购买成功时间',
  `s_id` int(11) DEFAULT NULL COMMENT '发货体，门店/仓库id',
  `publish_owner` tinyint(4) DEFAULT NULL COMMENT '发行方，门店的类型，1-妈妈好；2-winbb;3-swinnow',
  `card_from_record_id` int(11) DEFAULT NULL COMMENT 'A并B生成C C记录此值为A 其它情况为null',
  `card_unit_to_id` int(11) DEFAULT NULL COMMENT '从card_item_record_id并卡 老卡为新卡ID',
  `umember_id` int(11) DEFAULT NULL COMMENT 'upos系统会员id',
  `card_number` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联的会员卡号',
  `upgrade_from_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`card_item_record_id`),
  KEY `ORDER_NO` (`order_no`),
  KEY `index_orderLineId` (`order_line_id`) USING BTREE,
  KEY `index_umemberId` (`umember_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3341 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment '用户充值主表(查询数据仓库)';





CREATE TABLE `u_card_item_detail` (
  `card_item_detail_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '卡项内容表id',
  `card_item_record_id` int(11) DEFAULT NULL COMMENT '卡项购买记录关联表id',
  `service_id` int(11) DEFAULT NULL COMMENT '卡项内容id',
  `card_item_detail_type` tinyint(4) DEFAULT NULL COMMENT '卡项内容类型（综合卡的推拿、理发等，参见 u_service_item）',
  `card_item_detail_name` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '卡项内容名称（综合卡的推拿、理发等，参见 u_service_item）',
  `ori_value` int(11) DEFAULT NULL COMMENT '原始value（时间卡时，-99：有效期内无次数限制；大于0：每周可消费几次）',
  `rest_value` int(11) DEFAULT NULL COMMENT '剩余value',
  PRIMARY KEY (`card_item_detail_id`),
  KEY `index_cardRecordId` (`card_item_record_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4031 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment '用户余额明细(查询数据仓库)';


CREATE TABLE `t_voucher` (
  `voucher_id` int(11) NOT NULL AUTO_INCREMENT,
  `voucher_template_id` varchar(200) NOT NULL DEFAULT '0' COMMENT '优惠券模版ID',
  `voucher_group_id` varchar(200) DEFAULT NULL COMMENT '组券子id',
  `voucher_name` varchar(255) DEFAULT NULL COMMENT '优惠券名称',
  `order_no` varchar(255) DEFAULT NULL COMMENT '订单批次编号',
  `voucher_type` int(3) DEFAULT '0' COMMENT '优惠券类型:0=统一面额券， 1=礼包组合拳，3=卡券 4=红包',
  `voucher_grant_type` tinyint(3) DEFAULT '0' COMMENT '优惠券发放时间类型  0 不限时  1 定时',
  `grant_begin_time` datetime DEFAULT NULL COMMENT '定时发放开始日期',
  `grant_end_time` datetime DEFAULT NULL COMMENT '定时发放结束日期',
  `member_id` bigint(11) DEFAULT NULL COMMENT '领取人',
  `voucher_amount` int(11) DEFAULT '0' COMMENT '优惠券面额',
  `voucher_left_amount` int(11) DEFAULT '0' COMMENT '优惠券剩余金额',
  `voucher_use_money` int(11) DEFAULT '0' COMMENT '优惠券适用条件',
  `voucher_original_amount` int(11) DEFAULT '0' COMMENT '红包券初始面额',
  `voucher_property` int(3) DEFAULT '0' COMMENT '优惠券属性 0 单券 1组券(已废弃)',
  `voucher_valid_type` tinyint(3) DEFAULT '0' COMMENT '优惠券有效期类型 0 日期 1周期',
  `voucher_count` int(11) DEFAULT '0' COMMENT '优惠券发行数量',
  `exchange_type` tinyint(3) DEFAULT '0' COMMENT '兑换方式 0兑换码 1口令 2购买 3 摇一摇',
  `cd_key` varchar(255) DEFAULT NULL COMMENT '兑换码',
  `status` int(3) DEFAULT '0' COMMENT '0=未领取,1=已领取,2=取消使用,3=已使用，4=已失效',
  `obtain_time` datetime DEFAULT NULL COMMENT '领取时间',
  `use_time` datetime DEFAULT NULL COMMENT '使用时间',
  `expire_warn_time` datetime DEFAULT NULL COMMENT '过期提醒时间点',
  `begin_time` datetime DEFAULT NULL COMMENT '优惠券开始日期',
  `end_time` datetime DEFAULT NULL COMMENT '优惠券结束时间',
  `limit_count` int(11) DEFAULT '1' COMMENT '优惠券限领张数',
  `rule` tinyint(3) DEFAULT '0' COMMENT '是否与门店优惠可以叠加 0 不可  1 可以',
  `amount_index` int(3) unsigned DEFAULT '0' COMMENT 'amount_index 金额的种类索引，可以根据此来group by(已废弃)',
  `limit_part` int(3) DEFAULT '0' COMMENT '限领数量',
  `apply_type` tinyint(3) DEFAULT '0' COMMENT '默认勾选  0=全场通用， 1=指定品牌  2=指定类目  3=指定商品，4=复杂组合 5=红包',
  `apply_value` varchar(5000) DEFAULT '' COMMENT '已废弃，使用关系表维护',
  `apply_text` varchar(255) DEFAULT NULL COMMENT '适用范围文案',
  `voucher_cost` tinyint(3) DEFAULT '0' COMMENT '优惠券成本  默认勾选:0 集团承担  1 平台承担',
  `ticketid` varchar(50) DEFAULT '0',
  `title` varchar(31) DEFAULT NULL COMMENT '卡券主标题',
  `sub_title` varchar(31) DEFAULT NULL COMMENT '卡券副标题',
  `scope_channel` int(11) NOT NULL DEFAULT '0' COMMENT '适用消费渠道：0=不限，1=APP，2=门店POS+特卖会，3=门店POS，4=特卖会POS，5=APP + 门店POS，6=APP + 特卖会POS',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
  `index_of_group` int(11) NOT NULL DEFAULT '0' COMMENT '在组中的index，从0开始',
  `coupon_template_id_crc32` bigint(20) NOT NULL DEFAULT '0' COMMENT '对模板id进行crc32,转成长整形，方便索引',
  `discount_type` int(11) NOT NULL DEFAULT '0' COMMENT '优惠券面额类型：0=普通券，1=代金券（不限消费额） 3=红包',
  `decrease_type` int(11) NOT NULL DEFAULT '0' COMMENT '优惠券优惠类型 0-满减券，1-满折券 2=红包',
  `comb_type` int(11) NOT NULL DEFAULT '0' COMMENT '优惠券的叠加类别:0=红（全场通用 || APP + 优惠券）,1=紫（POS + 优惠券）,2=绿（APP  || 全场 + 优惠券）',
  `verification_code` int(1) DEFAULT '0' COMMENT '是否显示核销二维码 0：否 1：是',
  `gb_synchronous` int(1) DEFAULT '0' COMMENT '是否同步到GB 0：否 1：是',
  `max_reduce_amount` int(11) DEFAULT '0' COMMENT '翻倍券最高减金额 大于>0 有最高减',
  `sort_num` int(2) DEFAULT '0' COMMENT '排序 越大越靠前',
  PRIMARY KEY (`voucher_id`),
  KEY `INDEX_VOUCHER_ID` (`voucher_id`) USING BTREE,
  KEY `INDEX_VOUCHER_TEMPLATE_ID` (`voucher_template_id`) USING BTREE,
  KEY `INDEX_STATUS` (`status`) USING BTREE,
  KEY `INDEX_PROPERTY` (`voucher_property`) USING BTREE,
  KEY `INDEX_VOUCHER_GROUP_ID` (`voucher_group_id`) USING BTREE,
  KEY `INDEX_CD_KEY` (`cd_key`) USING BTREE,
  KEY `INDEX_T_STATUS` (`voucher_template_id`,`status`),
  KEY `IDX_MEMBER_ID` (`member_id`),
  KEY `IDX_VOUCHER_AMOUNT` (`voucher_amount`),
  KEY `IDX_SCOPE_CHANNEL` (`scope_channel`) USING BTREE,
  KEY `IDX_COUPON_TEMPLATE_ID_CRC32` (`coupon_template_id_crc32`) USING BTREE,
  KEY `INDEX_STATUSTIME` (`status`,`create_time`),
  KEY `voucher_type` (`voucher_type`)
) ENGINE=InnoDB AUTO_INCREMENT=8552239 DEFAULT CHARSET=utf8 comment '红包及优惠券(查询数据仓库)';




CREATE TABLE `u_achievement_percentage_record` (
  `record_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '提成记录ID',
  `member_id` int(11) DEFAULT NULL COMMENT '妈妈好会员ID',
  `shop_id` bigint(11) DEFAULT NULL COMMENT '店铺/仓库ID',
  `shop_name` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '店铺/仓库名称',
  `staff_id` int(11) NOT NULL COMMENT '员工工号',
  `staff_work_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '员工编号',
  `staff_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '员工名称',
  `item_num_id` bigint(20) DEFAULT NULL COMMENT '商品id',
  `good_item_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品名称',
  `item_count` int(11) DEFAULT NULL COMMENT '商品数量',
  `goods_div_num_id` int(11) DEFAULT NULL COMMENT '商品所属事业部ID',
  `order_no` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户订单号',
  `order_line_id` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单行id',
  `order_channel` int(1) NOT NULL DEFAULT '1' COMMENT '订单渠道(1-线下门店pos机；2-妈妈好APP)',
  `monetary` decimal(11,2) NOT NULL COMMENT '用户实付商品金额,单位元',
  `income` decimal(11,2) NOT NULL COMMENT '实付商品金额 * 佣金比率 单位元(佣金提成)',
  `collect_income` decimal(11,2) DEFAULT '0.00' COMMENT '总提成,单位元',
  `calculate_ratio` decimal(11,2) DEFAULT '1.00' COMMENT '计算比率',
  `pay_type` int(11) DEFAULT '0' COMMENT '支付方式：1-非余额支付 2-winbb 3-swimlove 4-mamahao',
  `payable_amount` decimal(11,2) DEFAULT '0.00' COMMENT '应付商品金额,单位元',
  `shop_type` int(11) DEFAULT NULL COMMENT '店铺类型，1-妈妈好门店，2-仓库',
  `order_buy_type` int(11) NOT NULL DEFAULT '1' COMMENT '订单购买类型，1-正常购买订单 2-退货订单',
  `return_order_no` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退货-原订单编号',
  `return_order_line_id` int(32) DEFAULT NULL COMMENT '退货-原订单行编号',
  `return_order_pay_time` datetime DEFAULT NULL COMMENT '退货-原订单支付时间',
  `programme_mode` int(11) DEFAULT NULL COMMENT '方案模式1：满金额，2:满数量',
  `mode_money` decimal(11,2) DEFAULT NULL COMMENT '满金额',
  `mode_num` int(11) DEFAULT NULL COMMENT '满数量',
  `reward_type` int(11) DEFAULT NULL COMMENT '奖励类型:1.全额奖励 2.实付金额比例',
  `reward_money` decimal(11,2) DEFAULT NULL COMMENT '全额奖励 ：金额',
  `reward_online` decimal(6,3) DEFAULT NULL COMMENT '线上奖励提成% 存小数',
  `reward_underline` decimal(6,3) DEFAULT NULL COMMENT '线下奖励提成% 存小数',
  `sport_goods_ratio` decimal(11,2) DEFAULT NULL COMMENT '运动类商品提成比率',
  `other_goods_ratio` decimal(11,2) DEFAULT NULL COMMENT '非运动类商品提成比率',
  `percentage_type` int(11) DEFAULT NULL COMMENT '提成方案类型，1-mpos门店提成方案 2-集团门店提成方案',
  `goods_type` int(11) DEFAULT NULL COMMENT '商品类型，1-运动商品 2-非运动商品',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `reward_discount` decimal(3,2) DEFAULT NULL COMMENT '商品的促销价低于品牌价x折',
  `bonus_online` decimal(11,2) DEFAULT NULL COMMENT '线上奖金提成 元',
  `bonus_underline` decimal(11,2) DEFAULT NULL COMMENT '线下奖金提成 元',
  `doubling` tinyint(4) DEFAULT NULL COMMENT '是否翻倍，1-翻倍 0-不翻倍',
  `programme_id` int(11) DEFAULT NULL COMMENT '对应的提成方案ID',
  `replenishment` tinyint(1) DEFAULT NULL COMMENT '1 ：后补订单 其他都是正常订单',
  `staff_type` int(11) DEFAULT NULL COMMENT '1-服务员工 2-绑定员工 3-充值员工 4-平台默认员工',
  PRIMARY KEY (`record_id`),
  KEY `index_order_no` (`order_no`(191)) USING BTREE,
  KEY `index_order_line_id` (`order_line_id`(191)) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=201628 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='提成记录表(查询数据仓库)';


drop table if exists t_crm_asset_count;

/*==============================================================*/
/* Table: t_crm_asset_count                                     */
/*==============================================================*/
create table t_crm_asset_count
(
   seq_id               bigint(20) comment '自增序列',
   member_id            bigint(11) comment '会员ID',
   member_phone         national varchar(20) not null comment '会员手机号',
   total_recharge_price decimal(20,2) comment '历史充值合计',
   total_balance        decimal(20,2) comment '剩余可用余额',
   total_used_price     decimal(20,2) comment '已使用余额',
   total_used_mbean     bigint(20) comment '已使用妈豆',
   used_mbean_percent   int(11) comment '妈豆使用率',
   total_voucher_left_amount decimal(20,2) default 0 comment '优惠券剩余金额',
   total_voucher_left_num int(11) comment '优化券剩余数量',
   total_used_voucher_amount decimal(20,2) comment '已使用优惠券金额',
   total_used_voucher_count int(11) comment '已使用优化券数量',
   used_voucher_percent float comment '优惠券使用率',
   total_red_packet_left_amount decimal(20,2) default 0 comment '红包剩余金额',
   total_red_packet_lef_left_num int(11) comment '红包剩余数量',
   total_used_red_packet_amount decimal(20,2) comment '已使用红包金额',
   total_used_red_packet_count int(11) comment '已使用红包数量',
   used_red_packet_percent float comment '红包使用率'
);

alter table t_crm_asset_count comment '资产信息';


drop table if exists t_crm_consume_analyse;

/*==============================================================*/
/* Table: t_crm_consume_analyse                                 */
/*==============================================================*/
create table t_crm_consume_analyse
(
   seq_id               bigint(20) comment '自增序列',
   member_id            bigint(11) comment '会员ID',
   member_phone         national varchar(20) not null comment '会员手机号',
   total_consume_price  decimal(20,2) comment '总消费',
   consume_price_ranking bigint(20) comment '消费排名',
   online_total_consume_price decimal(20,2) comment '线上消费总额',
   offline_total_consume_price decimal(20,2) comment '线下消费总额',
   online_total_refund_price decimal(20,2) comment '线上退款总额',
   offline_total_refund_price decimal(20,2) comment '线下消费总额',
   online_total_consume_num bigint(20) comment '线上消费次数',
   online_total_refund_num bigint(20) comment '线上售后次数',
   offline_total_refund_num bigint(20) comment '线下售后次数',
   offline_total_consume_num bigint(20) comment '线下消费次数',
   online_per_customer_transaction decimal(20,2) comment '线上客单价',
   often_consume_sid_id bigint(20) comment '经常消费门店ID',
   offline_per_customer_transaction decimal(20,2) comment '线下客单价',
   often_consume_sid    varchar(32) comment '经常消费门店',
   last_consume_datetime datetime comment '最近消费日期',
   love_brands          varchar(32) comment '品牌喜好',
   love_category        varchar(32) comment '类目喜好',
   often_purchase_goods varchar(225) comment '常购商品'
);

alter table t_crm_consume_analyse comment '消费分析';


drop table if exists t_crm_contact_note;

/*==============================================================*/
/* Table: t_crm_contact_note                                    */
/*==============================================================*/
create table t_crm_contact_note
(
   seq_id               bigint(20) comment '自增序列',
   member_id            bigint(11) comment '会员ID',
   member_phone         national varchar(20) not null comment '会员手机号',
   contact_type         bigint(11) comment '联系类型',
   contact_type_name    varchar(20) comment '联系类型名称',
   contact_value        varchar(1024) comment '内容表示',
   staff_id             bigint(11) comment '操作员ID',
   staff_name           varchar(32) comment '操作员名称',
   create_time          datetime comment '创建时间'
);

alter table t_crm_contact_note comment '联系笔记';



drop table if exists t_crm_member_info;

/*==============================================================*/
/* Table: t_crm_member_info                                     */
/*==============================================================*/
create table t_crm_member_info
(
   seq_id               bigint(20) comment '自增序列',
   member_id            bigint(11) comment '会员ID',
   member_phone         national varchar(20) not null comment '会员手机号',
   member_name          national varchar(64) comment '家长姓名',
   member_level_id      int(11) default 0 comment '会员级别ID',
   member_level_name    int(11) default 0 comment '会员级别',
   member_src           int(11) comment '会员来源',
   member_src_id        varchar(32) comment '会员来源ID',
   member_status        int(1) comment '身份状态:0 未选择，1 孕妈，2 宝妈，3备孕',
   baby_nickname        national varchar(255) comment '大宝姓名',
   baby_gender          int(1) comment '大宝性别：1 男，2 女',
   baby_birthday        date comment '大宝生日',
   baby_nickname_second national varchar(255) comment '小宝名称',
   baby_gender_second   int(1) comment '小宝性别：1 男，2 女',
   baby_birthday_second date comment '小宝生日'
);

alter table t_crm_member_info comment '会员信息';

drop table if exists t_crm_member_label;

/*==============================================================*/
/* Table: t_crm_member_label                                    */
/*==============================================================*/
create table t_crm_member_label
(
   seq_id               bigint(20) comment '自增序列',
   member_id            bigint(11) comment '会员ID',
   member_phone          varchar(20) not null comment '会员手机号',
   label_value          varchar(32) comment '标签名称'
);

alter table t_crm_member_label comment '会员标签';

